# !- Content Details
collections:

# !- Site Configuration
url: "" # primary url the website will reside at
title: "Example Site" # Site title
title-safe: "example-site" # Url safe version of site title. eg: "lowercase-dash-separated-text"
title-delimiter: " • " # Symbol to separate page title and site title. Include spaces. eg: "Home • Site Title"
tagline: "The exampliest site" # Website tagline
license: "GNU GPL v3 http://www.gnu.org/licenses/gpl-3.0.en.html"
copyright: "Example Site" # Will format out to "©{year} Example Site"
webmaster: "info@example.com" # email address for master of website
lang: "en_US" # base language for website
logo: "/assets/site-logo.png"
keywords: "" # Keywords to describe website
description: "" # Written description of website. Keep under 250 words if possible
author: "" # Site Author

fonts: true
# !- Publishing Information
creator: "@example" # Name or twitter handle of the website creator
email: "creator@exaple.com" # email address of website creator

# !- Social
social:
  name: Example Site
  links:
    - https://twitter.com/example
    - https://facebook.com/example
    - https://linkedin.com/in/example
    - https://plus.google.com/+example
    - https://github.com/example
twitter:
  username: "@example" # Twitter handle for website
facebook:
  app_id: "" # Facebook app ID for Facebook Insights
  publisher: "" # Facebook page url or ID for publishing entity
  admins: "" # Facebook user id for domain insights linked to a personal account

# !- analytics
# Does not load in development
analytics:        "UA-XXXXXX-XX" # Google analytics tracking number. eg "UA-XXXXXX-XX"
webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234
  baidu: 1234

# RSS - https://github.com/jekyll/jekyll-feed
feed:
  path: /feed.xml

# !- Mobile
mobile-optimized: true # is the website mobile optimized. true | false

# !- Web App Options
web-app-enabled: false # options: true | false
web-app-capable: "" # yes | no
web-app-title:   "" # tip: keep it short
web-app-style:   "" # options: default, black, black-translucent
web-app-color:   "" # used for Windows 8 / RT

# !- dns-prefetch
# Identifies a DNS query to resolve the background, so that requests can occur more quickly.
#dns-prefetch:
#  - twitter.com
#  - facebook.com
#  - mailchimp.com

# !- resource-prefetch:
# Identifies a resource file, such as an image or a CSS stylesheet, to be downloaded into the cache.
#prefetch:
#  - "http://example.com/css/style.css"
